### ISSUE TITLE
Undeclared require

### ISSUE THREAD

**Issue by iamkallolpratim** [scotch-io/building-and-securing-a-modern-backend-api#1]
On `server.js` file
`var express = require('express');`

jshint show a error that **Undeclared require**

**Comment by adocomplete** [comment]
Hey @iamkallolpratim - you may be seeing this error because your .jshintrc file does not have node enabled, so it is not aware of the global node functions and variables.

You can either add `/* jshint node: true */` to the top of your server.js file or add `{ node: true}` in your .jshintrc file.

Let me know if that helps.
